import { SystemRole } from '@automotive-os/types';
export declare const PERMISSIONS: {
    readonly CUSTOMERS_READ: "customers.read";
    readonly CUSTOMERS_CREATE: "customers.create";
    readonly CUSTOMERS_UPDATE: "customers.update";
    readonly CUSTOMERS_DELETE: "customers.delete";
    readonly VEHICLES_READ: "vehicles.read";
    readonly VEHICLES_CREATE: "vehicles.create";
    readonly VEHICLES_UPDATE: "vehicles.update";
    readonly VEHICLES_DELETE: "vehicles.delete";
    readonly INSPECTIONS_READ: "inspections.read";
    readonly INSPECTIONS_CREATE: "inspections.create";
    readonly INSPECTIONS_UPDATE: "inspections.update";
    readonly MEDIA_READ: "media.read";
    readonly MEDIA_UPLOAD: "media.upload";
    readonly MEDIA_DELETE: "media.delete";
    readonly WORK_ORDERS_READ: "work_orders.read";
    readonly WORK_ORDERS_CREATE: "work_orders.create";
    readonly WORK_ORDERS_UPDATE: "work_orders.update";
    readonly WORK_ORDERS_CLOSE: "work_orders.close";
    readonly WORK_ORDER_ITEMS_READ: "work_order_items.read";
    readonly WORK_ORDER_ITEMS_CREATE: "work_order_items.create";
    readonly WORK_ORDER_ITEMS_UPDATE: "work_order_items.update";
    readonly WORK_ORDER_ITEMS_DELETE: "work_order_items.delete";
    readonly DOCUMENTS_READ: "documents.read";
    readonly DOCUMENTS_CREATE: "documents.create";
    readonly DOCUMENTS_UPDATE: "documents.update";
    readonly DOCUMENTS_DELETE: "documents.delete";
    readonly TASKS_READ: "tasks.read";
    readonly TASKS_CREATE: "tasks.create";
    readonly TASKS_UPDATE: "tasks.update";
    readonly TASKS_DELETE: "tasks.delete";
    readonly REMINDERS_READ: "reminders.read";
    readonly REMINDERS_CREATE: "reminders.create";
    readonly REMINDERS_UPDATE: "reminders.update";
    readonly REPORTS_READ: "reports.read";
    readonly USERS_READ: "users.read";
    readonly USERS_CREATE: "users.create";
    readonly USERS_UPDATE: "users.update";
    readonly USERS_DELETE: "users.delete";
    readonly ROLES_READ: "roles.read";
    readonly ROLES_UPDATE: "roles.update";
    readonly ORGANIZATION_READ: "organization.read";
    readonly ORGANIZATION_UPDATE: "organization.update";
    readonly ORGANIZATION_DELETE: "organization.delete";
    readonly LOCATIONS_READ: "locations.read";
    readonly LOCATIONS_CREATE: "locations.create";
    readonly LOCATIONS_UPDATE: "locations.update";
    readonly LOCATIONS_DELETE: "locations.delete";
    readonly BACKUP_CREATE: "backup.create";
    readonly BACKUP_RESTORE: "backup.restore";
    readonly AUDIT_READ: "audit.read";
};
export declare const ROLE_PERMISSIONS: Record<SystemRole, string[]>;
export declare function hasPermission(userPermissions: string[], requiredPermission: string): boolean;
