FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY packages/ packages/
COPY apps/api/ apps/api/
RUN npm install
RUN npm run build --workspace=packages/types
RUN npm run build --workspace=packages/permissions
RUN npm run build --workspace=packages/config
RUN npm run build --workspace=packages/api-client

EXPOSE 4000
CMD ["npm", "run", "start", "--workspace=apps/api"]
